### ISSUE TITLE
Can not change leading icon

### ISSUE THREAD

**Issue by Fredricknjeri** [oaktreeapps/stacked_notification_cards#11]

**Comment by pkhivesara** [comment]
Hi @Fredricknjeri thanks for creating the ticket. Can you help us understand the use case for changing the leading icon? Are you trying to add functionality or is this purely from UI/UX decision? 

Can you also provide a sample image of the leading icon that you are trying to use?

**Comment by pkhivesara** [comment]
Hi @Fredricknjeri, the issue was resolved in the latest update of the package. Give it a shot and let us know if there are any issues. Thanks!
