### ISSUE TITLE
Optional Leading Icon not Implemented yet

### ISSUE THREAD

**Issue by Habutaki** [oaktreeapps/stacked_notification_cards#12]
Hello, 

I am using this package for a project and everything works perfectly fine except that I do not want to have a leading icon in the notifications. I have seen past closed issues discussing the same thing with having the leading icon not being a required field or having a card with flexible format. However, I see none implemented on the latest version of this package. 
I see that there was a pull request with the title "Ability to have no leading as well as modify leading correctly. #2" that has been under review a sometime. Can these changes be merged and pushed to pub.dev?

**Comment by pkhivesara** [comment]
Hi @Habutaki,

Hi @Fredricknjeri thanks for creating the ticket. We will explore the use case and have a update to the package as soon as we can!

**Comment by pkhivesara** [comment]
Hi @Habutaki, the issue was resolved in the latest update of the package. Give it a shot and let us know if there are any issues. Thanks!
