### ISSUE TITLE
intl upgrade to last version

### ISSUE THREAD

**Issue by BrunoC96** [oaktreeapps/stacked_notification_cards#5]
Hi,
I wanna use this library but I can't because, `intl` dependency in my project is `0.18.0`, and can't downgrade it for other dependency issue. It is possible to upgrade this package to have `intl` from `0.17.0` to `0.18.0`.

**Comment by pkhivesara** [comment]
Hello @BrunoC96, we have a new update out which fixes this. Please test with 0.1.0-dev.4 and let us know if the issue still persists. Thanks!
